version: "3.9"
services:
  web:
    build:
      context: .
      args:
        PORT: 8501
    ports:
      - "8501:8501"
    environment:
      - NLTK_DATA=/root/nltk_data
    command: streamlit run app/main.py --server.port 8501 --server.address=0.0.0.0
    volumes:
      - .:/app
      - cares_app:/root
      # - ./model_data:/root

volumes:
  cares_app: